---

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    # Base
    - build-essential
    - curl
    - git
    - git-flow
    - jq
    - less
    - libssl-dev
    - tmux
    - tig
    - unzip
    - vim
    - wget
    - zlib1g-dev
    # For bash
    - bash-completion
    # For ping
    - iputils-ping
    # For updatedb
    - mlocate
    # For autotools
    - autoconf
    - automake
    - libtool

- name: Clone dotfiles
  git:
    repo: "https://github.com/sato-mh/dotfiles.git"
    dest: "~/.dotfiles"

- name: Set symbolic links
  shell: "bash ~/.dotfiles/set-symbolic-links.sh"

- name: Configure git username
  shell: "git config --global user.name {{ git_user }}"

- name: Configure git email
  shell: "git config --global user.email {{ git_email }}"

- name: Configure git editor
  shell: "git config --global core.editor {{ git_editor }}"

- name: Configure git excludesfile
  shell: "git config --global core.excludesfile '~/.gitignore'"

- name: Make directory for src
  file:
    path: "~/src"
    state: directory
    mode: 0755

- name: Git Clone bash-completion
  git:
    repo: "https://github.com/scop/bash-completion.git"
    dest: "~/src/bash-completion"

- name: Prepare installation of bash-completion
  shell: "autoreconf -i && ./configure && make"
  args:
    chdir: "~/src/bash-completion"

- name: Install bash-completion
  become: yes
  shell: "make install"
  args:
    chdir: "~/src/bash-completion"

- name: Download openssh-7.6p1
  shell: "wget http://ftp.jaist.ac.jp/pub/OpenBSD/OpenSSH/portable/openssh-7.6p1.tar.gz"
  args:
    chdir: "~/src"

- name: Unarchive openssh-7.6p1
  unarchive:
      src: "~/src/openssh-7.6p1.tar.gz"
      dest: "~/src"
      remote_src: yes

- name: Prepare installation of openssh-7.6p1
  shell: "./configure && make"
  args:
    chdir: "~/src/openssh-7.6p1"

- name: install openssh-7.6p1
  become: yes
  shell: "make install"
  args:
    chdir: "~/src/openssh-7.6p1"
